apiVersion: v1
kind: Pod
metadata:
  labels:
    run: salatux
    service: webserver
  name: salatux
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /salatux-volume
      name: volume-salatux-emptydir
    args:
    resources:
      limits:
        cpu: "1"
        memory: "256Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: volume-salatux-emptydir
    emptyDir:
      sizeLimit: 64Mi

