apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-faminto
  name: pod-faminto
  namespace: treinamento-ch2
spec:
  containers:
  - args:
    image: polinux/stress
    name: pod-faminto
    resources: 
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["stress"]
    args:
      - "--vm"
      - "1"
      - "--vm-bytes"
      - "250M"
      - "--vm-hang"
      - "1"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
